In [8]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt



In [9]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [10]:

observations=1000
xs=np.random.uniform(-10,10,(observations,1))
zs=np.random.uniform(-10,10,(observations,1))
generated_inputs=np.column_stack((xs,zs))
noise=np.random.uniform(-1,1,(observations,1))
generated_targets=2*xs-3*zs+5+noise

np.savez('TF_intro',inputs_new=generated_inputs,targets_new=generated_targets)

In [11]:
training_data=np.load('TF_intro.npz')

input_size=2
output_size=1

In [12]:
model=Sequential()
model.add(Dense(output_size))

model.compile(optimizer='sgd',loss='mean_squared_error')

In [13]:
model.fit(training_data['inputs_new'],training_data['targets_new'],epochs=100,verbose=0)

In [14]:
model.fit(training_data['inputs_new'],training_data['targets_new'],epochs=100,verbose=1)

Epoch 1/100
1000/1000 [==============================] - 0s 31us/sample - loss: 0.3331
Epoch 2/100
1000/1000 [==============================] - 0s 62us/sample - loss: 0.3349
Epoch 3/100
1000/1000 [==============================] - 0s 62us/sample - loss: 0.3304
Epoch 4/100
1000/1000 [==============================] - 0s 62us/sample - loss: 0.3230
Epoch 5/100
1000/1000 [==============================] - 0s 62us/sample - loss: 0.3308
Epoch 6/100
1000/1000 [==============================] - 0s 62us/sample - loss: 0.3305
Epoch 7/100
1000/1000 [==============================] - 0s 63us/sample - loss: 0.3307
Epoch 8/100
1000/1000 [==============================] - 0s 62us/sample - loss: 0.3299
Epoch 9/100
1000/1000 [==============================] - 0s 63us/sample - loss: 0.3387
Epoch 10/100
1000/1000 [==============================] - 0s 47us/sample - loss: 0.3342
Epoch 11/100
1000/1000 [==============================] - 0s 62us/sample - loss: 0.3303
Epoch 12/100
1000/1000 [=================

1000/1000 [==============================] - 0s 47us/sample - loss: 0.3284
Epoch 95/100
1000/1000 [==============================] - 0s 47us/sample - loss: 0.3387
Epoch 96/100
1000/1000 [==============================] - 0s 62us/sample - loss: 0.3361
Epoch 97/100
1000/1000 [==============================] - 0s 31us/sample - loss: 0.3318
Epoch 98/100
1000/1000 [==============================] - 0s 47us/sample - loss: 0.3331
Epoch 99/100
1000/1000 [==============================] - 0s 47us/sample - loss: 0.3285
Epoch 100/100
1000/1000 [==============================] - 0s 47us/sample - loss: 0.3370


In [57]:
##extract weights and biases

In [58]:
model.layers[0].get_weights()

[array([[ 2.0214643],
        [-2.9996858]], dtype=float32),
 array([4.9738], dtype=float32)]

In [61]:
weights=model.layers[0].get_weights()[0]
weights

array([[ 2.0214643],
       [-2.9996858]], dtype=float32)

In [62]:
bias=model.layers[0].get_weights()[1]
bias

array([4.9738], dtype=float32)

In [72]:
predict=model.predict_on_batch(training_data['inputs_new'])
np.array(predict).round(1)

array([[ 20.1],
       [ -5.4],
       [ -4.5],
       [ 22.3],
       [-36.3],
       [ 14.6],
       [ 15.9],
       [ 17.3],
       [-14.6],
       [ 11.7],
       [  3.4],
       [-20.9],
       [ -0.5],
       [-16.4],
       [  4. ],
       [ 24. ],
       [-30.4],
       [-18.7],
       [ 16.2],
       [-16.8],
       [ 22.5],
       [-15.2],
       [ -3.5],
       [ -8.6],
       [ -0.2],
       [ 14.1],
       [ 36.8],
       [  5.5],
       [ 37.8],
       [ 32. ],
       [ 27.5],
       [ 23.6],
       [  3.5],
       [-26.5],
       [-15.7],
       [ 16.3],
       [  4. ],
       [-40.1],
       [ -6. ],
       [ 22. ],
       [ 19.4],
       [-16.2],
       [ 13.9],
       [ -8. ],
       [-23.5],
       [  3.8],
       [-25.6],
       [ 14.4],
       [ 16.3],
       [-22.5],
       [-25. ],
       [ 19.3],
       [  7.4],
       [ 17.1],
       [-19.6],
       [  2.5],
       [ 13.4],
       [  7.1],
       [ -0.6],
       [  7.6],
       [ 26.4],
       [ 28.1],
       [

In [ ]:
np.array(generated_targets).round(1)