In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [7]:
a=np.arange(1,101)
b=np.arange(501,601)

In [8]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [14]:
train_test_split(a)                           # by default 75,25    and suffuled array

[array([ 78,  21,  39,  11,  61,  65,  14,  52,   8,  86,  94,  53,  99,
         30,  25,  33,  92,  10,  91,  48,  72,  41,  59,  29,  15,  70,
         43,   5,  75,  32,  37,   3,  60,  20,  23,  83,  40,  42,  96,
         84,  28,  97,  80,  76,  12,  34,  63,  35,  66,  17,  87,   9,
         68,  57,  45,  26,  74,  27,  18,  89,  38,  71,   1,   6,  51,
         90, 100,  31,  47,  62,  22,   7,  95,  56,  49]),
 array([55, 54, 13, 50, 93, 82,  2, 19, 24,  4, 16, 46, 98, 77, 88, 36, 73,
        44, 67, 58, 69, 81, 85, 79, 64])]

In [19]:
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.2)   # it suffules the data in every run so for consistant result
#  we have to give random_state=42

In [20]:
a_train.shape , a_test.shape

((80,), (20,))

In [21]:
a_train,a_test

(array([ 38,  93,  82,  67,  25,  16,  84,   5,  70,  36,  37,  59,  14,
         68,  45,   6,  50,  61,   7,  57,  71,   2,  48,  92,  13,  91,
         35,  27,  66,  79,  56,  52,  85,  20,  44,  74,  72,  46,  39,
         23,   4,  75,  17,  60,  98,  62,   1,  30,  77,  86,  69,  64,
         28,  26,  22,  63,  41,  53,  99,  29,  87,   8,  40,  15,  95,
         65,  51,  81,  11,  31,  54,  76,  18,  33,  89,  58,  21,  10,
        100,  55]),
 array([97, 32, 34,  9, 42, 43, 47, 73, 24, 78, 90, 96, 19, 88, 83, 80, 49,
        12, 94,  3]))

In [24]:
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.2,random_state=42) 
a_train,a_test

(array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
         29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
         82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
         90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
         59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
         53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
         93,  52]),
 array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
        78, 13, 32]))

In [25]:
b_train,b_test

(array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
        529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
        582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
        590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
        559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
        553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
        593, 552]),
 array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
        534, 591, 505, 577, 578, 513, 532]))